topic_template_placeholder_indicator:
  type: list
  default: '<!--placeholder-->' 
  description: '<h4>Instructions:</h4><b>Include &lt;!--placeholder--&gt; at the start of your Topic Template text</b><br><br>This will make it display as a placeholder (watermark text) instead of as editable template text.<br><br>Simply remove the &lt;--placeholder--$gt; to change it back to template text.<br><br>You can change &lt;!--placeholder--&gt; to another word of phrase by editing this list.'
